window.ammo = [
    {
      "class": ".22lr round",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".22lr round",
      "Name": "plinking",
      "Dam": 0.85,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".22lr round",
      "Name": "hollow point",
      "Dam": 1.75,
      "DT": 3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".308 round",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".308 round",
      "Name": "armor piercing",
      "Dam": 0.95,
      "DT": -15,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".308 round",
      "Name": "JSP (hand load)",
      "Dam": 1.3,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".308 round",
      "Name": "hollowpoint",
      "Dam": 1.75,
      "DT": 3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".357 Magnum round ",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".357 Magnum round ",
      "Name": ".38 special round",
      "Dam": 0.75,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".357 Magnum round ",
      "Name": "JFP (hand load)",
      "Dam": 1.25,
      "DT": -3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".357 Magnum round ",
      "Name": "hollow point",
      "Dam": 1.75,
      "DT": 3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".44 Magnum round",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".44 Magnum round",
      "Name": ".44 special round",
      "Dam": 0.75,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".44 Magnum round",
      "Name": "SWC (hand load)",
      "Dam": 1.2,
      "DT": -6,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".44 Magnum round",
      "Name": "hollow point",
      "Dam": 1.75,
      "DT": 3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45 auto",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45 auto",
      "Name": "+P",
      "Dam": 1.1,
      "DT": -2,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45 auto",
      "Name": "super (hand load)",
      "Dam": 1.3,
      "DT": -4,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45 auto",
      "Name": "hollow point",
      "Dam": 1.75,
      "DT": 3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45-70 Gov't",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45-70 Gov't",
      "Name": "SWC (hand load)",
      "Dam": 1.2,
      "DT": -6,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45-70 Gov't",
      "Name": "hollow point",
      "Dam": 1.75,
      "DT": 3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".50 mg",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".50 mg",
      "Name": "armor piercing",
      "Dam": 0.95,
      "DT": -15,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".50 mg",
      "Name": "match (hand load)",
      "Dam": 1.15,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".50 mg",
      "Name": "incendiary",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "2/5s",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".50 mg",
      "Name": "explosive",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "80",
      "robot": null,
      "PA": null
    },
    {
      "class": "5mm round",
      "Name": "standard",
      "Dam": 1,
      "DT": -10,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5mm round",
      "Name": "armor piercing",
      "Dam": 0.95,
      "DT": -25,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5mm round",
      "Name": "surplus",
      "Dam": 1.15,
      "DT": -10,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5mm round",
      "Name": "JSP (hand load)",
      "Dam": 1.3,
      "DT": -10,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5mm round",
      "Name": "hollow point",
      "Dam": 1.75,
      "DT": 2,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": ".223 round",
      "Dam": 0.9,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": "armor piercing",
      "Dam": 0.95,
      "DT": -15,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": "surplus",
      "Dam": 1.15,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": "match (hand load)",
      "Dam": 1.15,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": "hollow point",
      "Dam": 1.75,
      "DT": 3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "9mm round",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "9mm round",
      "Name": "+p",
      "Dam": 1.1,
      "DT": -2,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "9mm round",
      "Name": "JHP (hand load)",
      "Dam": 1.65,
      "DT": 2,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "9mm round",
      "Name": "hollow point",
      "Dam": 1.75,
      "DT": 3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "10mm round",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "10mm round",
      "Name": "JHP (hand load)",
      "Dam": 1.65,
      "DT": 2,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "10mm round",
      "Name": "hollow point",
      "Dam": 1.75,
      "DT": 3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12.7mm round",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12.7mm round",
      "Name": "JHP (hand load)",
      "Dam": 1.65,
      "DT": 2,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12.7mm round",
      "Name": "hollow point",
      "Dam": 1.75,
      "DT": 3,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge shotgun shell",
      "Name": "stardard",
      "Dam": 1.2,
      "DT": 1,
      "proj": 7,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge shotgun shell",
      "Name": "bean bag",
      "Dam": 0.05,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge shotgun shell",
      "Name": "pulse slug",
      "Dam": 0.7,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": 50,
      "PA": 25
    },
    {
      "class": "12 gauge shotgun shell",
      "Name": "flechette",
      "Dam": 0.9,
      "DT": -6,
      "proj": 5,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge shotgun shell",
      "Name": "dragon's breath",
      "Dam": 0.9,
      "DT": 1,
      "proj": 1,
      "dot": "8/5s",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge shotgun shell",
      "Name": "slug",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge shotgun shell",
      "Name": "4/0 buck",
      "Dam": 1,
      "DT": 1,
      "proj": 4,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge shotgun shell",
      "Name": "coin shot",
      "Dam": 1.3,
      "DT": -2,
      "proj": 8,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge shotgun shell",
      "Name": "magnum",
      "Dam": 1.3,
      "DT": -2,
      "proj": 7,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge shotgun shell",
      "Name": "4/0 buck magnum (handload)",
      "Dam": 1.3,
      "DT": -2,
      "proj": 4,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "20 gauge shotgun shell",
      "Name": "standard",
      "Dam": 1.2,
      "DT": 1,
      "proj": 7,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "20 gauge shotgun shell",
      "Name": "pulse slug",
      "Dam": 0.7,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": 50,
      "PA": 25
    },
    {
      "class": "20 gauge shotgun shell",
      "Name": "slug",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "20 gauge shotgun shell",
      "Name": "3/0 buck",
      "Dam": 1,
      "DT": 1,
      "proj": 4,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "20 gauge shotgun shell",
      "Name": "magnum",
      "Dam": 1.3,
      "DT": -2,
      "proj": 7,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "20 gauge shotgun shell",
      "Name": "3/0 buck magnum",
      "Dam": 1.3,
      "DT": -2,
      "proj": 4,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "25mm grenade",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "25mm grenade",
      "Name": "pulse",
      "Dam": 0.08,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": 75,
      "PA": 30
    },
    {
      "class": "25mm grenade",
      "Name": "timed",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "25mm grenade",
      "Name": "plasma",
      "Dam": 1.3,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "25mm grenade",
      "Name": "high explosive",
      "Dam": 1.35,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "40mm grenade",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "40mm grenade",
      "Name": "pulse",
      "Dam": 0.08,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": 150,
      "PA": 60
    },
    {
      "class": "40mm grenade",
      "Name": "incendiary",
      "Dam": 0.75,
      "DT": 1,
      "proj": 1,
      "dot": "6/15s",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "40mm grenade",
      "Name": "plasma",
      "Dam": 1.3,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "missile",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "missile",
      "Name": "high velocity",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "missile",
      "Name": "high explosive",
      "Dam": 1.35,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "missile",
      "Name": "hive",
      "Dam": 1.58,
      "DT": 1,
      "proj": 9,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "mini nuke",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "mini nuke",
      "Name": "low yield",
      "Dam": 0.67,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "mini nuke",
      "Name": "timed",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "mini nuke",
      "Name": "Big Kid",
      "Dam": 1.33,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "mini nuke",
      "Name": "Tiny Tots",
      "Dam": 1.88,
      "DT": 1,
      "proj": 9,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "rocket",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "rocket",
      "Name": "incendiary",
      "Dam": 0.75,
      "DT": 1,
      "proj": 1,
      "dot": "2/8s",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "rocket",
      "Name": "high explosive",
      "Dam": 1.35,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "Alien power cell",
      "Name": "Alien power cell",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "electron charge pack",
      "Name": "standard",
      "Dam": 1,
      "DT": -2,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "electron charge pack",
      "Name": "bulk",
      "Dam": 0.85,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "electron charge pack",
      "Name": "overcharge",
      "Dam": 1.25,
      "DT": -5,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "electron charge pack",
      "Name": "optimized",
      "Dam": 1.3,
      "DT": -5,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "electron charge pack",
      "Name": "max charge",
      "Dam": 1.5,
      "DT": -10,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "energy cell",
      "Name": "standard",
      "Dam": 1,
      "DT": -2,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "energy cell",
      "Name": "bulk",
      "Dam": 0.85,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "energy cell",
      "Name": "over charge",
      "Dam": 1.25,
      "DT": -5,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "energy cell",
      "Name": "optimized",
      "Dam": 1.3,
      "DT": -5,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "energy cell",
      "Name": "max charge",
      "Dam": 1.5,
      "DT": -10,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "flamer fuel",
      "Name": "standard",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "flamer fuel",
      "Name": "homemade",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "flamer fuel",
      "Name": "optimized",
      "Dam": 1.3,
      "DT": -5,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "microfusion cell",
      "Name": "standard",
      "Dam": 1,
      "DT": -2,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "microfusion cell",
      "Name": "bulk",
      "Dam": 0.85,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "microfusion cell",
      "Name": "overcharge",
      "Dam": 1.25,
      "DT": -5,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "microfusion cell",
      "Name": "optimized",
      "Dam": 1.3,
      "DT": -5,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "microfusion cell",
      "Name": "max charge",
      "Dam": 1.5,
      "DT": -10,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "Microfusion breeder",
      "Name": "Microfusion breeder",
      "Dam": 1,
      "DT": -2,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "BBs",
      "Name": "BBs",
      "Dam": 1,
      "DT": 1,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "Nails",
      "Name": "Nail",
      "Dam": 1,
      "DT": -5,
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    }
]