window.list = [
    {
        "Name": "Revolver",
        "Damage": 29,
        "Speed": 1.2,
        "Proj": 1,
        "CritMul": 5,
        "CritDam": 29,
        "Ammo": ".357 Magnum"
    },
    {
        "Name": "Shotgun",
        "Damage": 5,
        "Speed": 1.2,
        "Proj": 7,
        "CritMul": 5,
        "CritDam": 5,
        "Ammo": "20 gauge"
    }
]
window.ammo = [
    {
      "class": ".22lr round",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".22lr round",
      "Name": "plinking",
      "Dam": "x 0.85",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".22lr round",
      "Name": "hollow point",
      "Dam": "x 1.75",
      "DT": "x 3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".308 round",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".308 round",
      "Name": "armor piercing",
      "Dam": "x 0.95",
      "DT": "-15",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".308 round",
      "Name": "JSP (hand load)",
      "Dam": "x 1.3",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".308 round",
      "Name": "hollowpoint",
      "Dam": "x 1.75",
      "DT": "x 3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".357 Magnum",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".357 Magnum",
      "Name": ".38 special round",
      "Dam": "x 0.75",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".357 Magnum",
      "Name": "JFP (hand load)",
      "Dam": "x 1.25",
      "DT": "-3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".357 Magnum",
      "Name": "hollow point",
      "Dam": "x 1.75",
      "DT": "x 3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".44 magnum round",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".44 magnum round",
      "Name": ".44 special round",
      "Dam": "x 0.75",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".44 magnum round",
      "Name": "SWC (hand load)",
      "Dam": "x 1.2",
      "DT": "-6",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".44 magnum round",
      "Name": "hollow point",
      "Dam": "x 1.75",
      "DT": "x 3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45 auto",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45 auto",
      "Name": "+P",
      "Dam": "x 1.1",
      "DT": "-2",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45 auto",
      "Name": "super (hand load)",
      "Dam": "x 1.3",
      "DT": "-4",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45 auto",
      "Name": "hollow point",
      "Dam": "x 1.75",
      "DT": "x 3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45-70 gov't",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45-70 gov't",
      "Name": "SWC (hand load)",
      "Dam": "x 1.2",
      "DT": "-6",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".45-70 gov't",
      "Name": "hollow point",
      "Dam": "x 1.75",
      "DT": "x 3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".50 mg",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".50 mg",
      "Name": "armor piercing",
      "Dam": "x 0.95",
      "DT": "-15",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".50 mg",
      "Name": "match (hand load)",
      "Dam": "x 1.15",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".50 mg",
      "Name": "incendiary",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "2/5s",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": ".50 mg",
      "Name": "explosive",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "80",
      "robot": null,
      "PA": null
    },
    {
      "class": "5mm round",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "-10",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5mm round",
      "Name": "armor piercing",
      "Dam": "x 0.95",
      "DT": "-25",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5mm round",
      "Name": "surplus",
      "Dam": "x 1.15",
      "DT": "-10",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5mm round",
      "Name": "JSP (hand load)",
      "Dam": "x 1.3",
      "DT": "-10",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5mm round",
      "Name": "hollow point",
      "Dam": "x 1.75",
      "DT": "x 2",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": ".223 round",
      "Dam": "x 0.9",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": "armor piercing",
      "Dam": "x 0.95",
      "DT": "-15",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": "surplus",
      "Dam": "x 1.15",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": "match (hand load)",
      "Dam": "x 1.15",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "5.56mm round",
      "Name": "hollow point",
      "Dam": "x 1.75",
      "DT": "x 3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "9mm round",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "9mm round",
      "Name": "+p",
      "Dam": "x 1.1",
      "DT": "-2",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "9mm round",
      "Name": "JHP (hand load)",
      "Dam": "x 1.65",
      "DT": "x 2",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "9mm round",
      "Name": "hollow point",
      "Dam": "x 1.75",
      "DT": "x 3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "10mm round",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "10mm round",
      "Name": "JHP (hand load)",
      "Dam": "x 1.65",
      "DT": "x 2",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "10mm round",
      "Name": "hollow point",
      "Dam": "x 1.75",
      "DT": "x 3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12.7mm round",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12.7mm round",
      "Name": "JHP (hand load)",
      "Dam": "x 1.65",
      "DT": "x 2",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12.7mm round",
      "Name": "hollow point",
      "Dam": "x 1.75",
      "DT": "x 3",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge",
      "Name": "stardard",
      "Dam": "x 1.2",
      "DT": "x 1",
      "proj": 7,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge",
      "Name": "bean bag",
      "Dam": "x 0.05",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge",
      "Name": "pulse slug",
      "Dam": "x 0.7",
      "DT": "x 1",
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": 50,
      "PA": 25
    },
    {
      "class": "12 gauge",
      "Name": "flechette",
      "Dam": "x 0.9",
      "DT": "-6",
      "proj": 5,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge",
      "Name": "dragon's breath",
      "Dam": "x 0.9",
      "DT": "x 1",
      "proj": null,
      "dot": "8/5s",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge",
      "Name": "slug",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge",
      "Name": "4/0 buck",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": 4,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge",
      "Name": "coin shot",
      "Dam": "x 1.3",
      "DT": "-2",
      "proj": 8,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge",
      "Name": "magnum",
      "Dam": "x 1.3",
      "DT": "-2",
      "proj": 7,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "12 gauge",
      "Name": "4/0 buck magnum (handload)",
      "Dam": "x 1.3",
      "DT": "-2",
      "proj": 4,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "20 gauge",
      "Name": "standard",
      "Dam": "x 1.2",
      "DT": "x 1",
      "proj": 7,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "20 gauge",
      "Name": "pulse slug",
      "Dam": "x 0.7",
      "DT": "x 1",
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": 50,
      "PA": 25
    },
    {
      "class": "20 gauge",
      "Name": "slug",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": 1,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "20 gauge",
      "Name": "3/0 buck",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": 4,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "20 gauge",
      "Name": "magnum",
      "Dam": "x 1.3",
      "DT": "-2",
      "proj": 7,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "20 gauge",
      "Name": "3/0 buck magnum",
      "Dam": "x 1.3",
      "DT": "-2",
      "proj": 4,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "25mm grenade",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "25mm grenade",
      "Name": "pulse",
      "Dam": "x 0.08",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": 75,
      "PA": 30
    },
    {
      "class": "25mm grenade",
      "Name": "timed",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "25mm grenade",
      "Name": "plasma",
      "Dam": "x 1.3",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "25mm grenade",
      "Name": "high explosive",
      "Dam": "x 1.35",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "40mm grenade",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "40mm grenade",
      "Name": "pulse",
      "Dam": "x 0.08",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": 150,
      "PA": 60
    },
    {
      "class": "40mm grenade",
      "Name": "incendiary",
      "Dam": "x 0.75",
      "DT": "x 1",
      "proj": null,
      "dot": "6/15s",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "40mm grenade",
      "Name": "plasma",
      "Dam": "x 1.3",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "missile",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "missile",
      "Name": "high velocity",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "missile",
      "Name": "high explosive",
      "Dam": "x 1.35",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "missile",
      "Name": "hive",
      "Dam": "x 1.58",
      "DT": "x 1",
      "proj": 9,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "mini nuke",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "mini nuke",
      "Name": "low yield",
      "Dam": "x 0.67",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "mini nuke",
      "Name": "timed",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "mini nuke",
      "Name": "Big Kid",
      "Dam": "x 1.33",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "mini nuke",
      "Name": "Tiny Tots",
      "Dam": "x 1.88 (total)",
      "DT": "x 1",
      "proj": 9,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "rocket",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "rocket",
      "Name": "incendiary",
      "Dam": "x 0.75",
      "DT": "x 1",
      "proj": null,
      "dot": "2/8s",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "rocket",
      "Name": "high explosive",
      "Dam": "x 1.35",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "Alien power cell",
      "Name": "Alien power cell",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "electron charge pack",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "-2",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "electron charge pack",
      "Name": "bulk",
      "Dam": "x 0.85",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "electron charge pack",
      "Name": "overcharge",
      "Dam": "x 1.25",
      "DT": "-5",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "electron charge pack",
      "Name": "optimized",
      "Dam": "x 1.3",
      "DT": "-5",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "electron charge pack",
      "Name": "max charge",
      "Dam": "x 1.5",
      "DT": "-10",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "energy cell",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "-2",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "energy cell",
      "Name": "bulk",
      "Dam": "x 0.85",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "energy cell",
      "Name": "over charge",
      "Dam": "x 1.25",
      "DT": "-5",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "energy cell",
      "Name": "optimized",
      "Dam": "x 1.3",
      "DT": "-5",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "energy cell",
      "Name": "max charge",
      "Dam": "x 1.5",
      "DT": "-10",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "flamer fuel",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "flamer fuel",
      "Name": "homemade",
      "Dam": "x 1",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "flamer fuel",
      "Name": "optimized",
      "Dam": "x 1.3",
      "DT": "-5",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "microfusion cell",
      "Name": "standard",
      "Dam": "x 1",
      "DT": "-2",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "microfusion cell",
      "Name": "bulk",
      "Dam": "x 0.85",
      "DT": "x 1",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "microfusion cell",
      "Name": "overcharge",
      "Dam": "x 1.25",
      "DT": "-5",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "microfusion cell",
      "Name": "optimized",
      "Dam": "x 1.3",
      "DT": "-5",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "microfusion cell",
      "Name": "max charge",
      "Dam": "x 1.5",
      "DT": "-10",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "Microfusion breeder",
      "Name": "Microfusion breeder",
      "Dam": "x 1",
      "DT": "-2",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "BBs",
      "Name": "BBs",
      "Dam": "x 1",
      "DT": "0",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    },
    {
      "class": "Nail",
      "Name": "Nail",
      "Dam": "x 1",
      "DT": "-5",
      "proj": null,
      "dot": "",
      "exp": "",
      "robot": null,
      "PA": null
    }
]