window.list = [
  {
    "Name": ".357 Magnum revolver",
    "Damage": 29,
    "Exp": 0,
    "Reload": 0.6,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.75,
    "proj": 1,
    "Critical": 1,
    "CritDam": 26,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 26,
    "ammo": ".357 Magnum round",
    "Type": "Cowboy, Professional",
    "ClipSize": 6
  },
  {
    "Name": ".44 Magnum revolver",
    "Damage": 36,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.88,
    "proj": 1,
    "Critical": 1,
    "CritDam": 36,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": ".44 Magnum round",
    "Type": "Cowboy, Professional",
    "ClipSize": 6
  },
  {
    "Name": ".45 Auto pistol",
    "Damage": 29,
    "Exp": 0,
    "Reload": 1.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.75,
    "proj": 1,
    "Critical": 1,
    "CritDam": 29,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": ".45 Auto",
    "Type": "Grunt, Professional",
    "ClipSize": 7
  },
  {
    "Name": "10mm pistol",
    "Damage": 22,
    "Exp": 0,
    "Reload": 1.3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.75,
    "proj": 1,
    "Critical": 1,
    "CritDam": 22,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": "10mm round",
    "Type": "Professional",
    "ClipSize": 16
  },
  {
    "Name": "12.7mm pistol",
    "Damage": 40,
    "Exp": 0,
    "Reload": 1.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.75,
    "proj": 1,
    "Critical": 1,
    "CritDam": 40,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": "12.7mm round",
    "Type": "Professional",
    "ClipSize": 7
  },
  {
    "Name": "5.56mm pistol",
    "Damage": 28,
    "Exp": 0,
    "Reload": 2.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.75,
    "proj": 1,
    "Critical": 2,
    "CritDam": 28,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 21,
    "ammo": "5.56mm round",
    "Type": "Cowboy, Professional",
    "ClipSize": 5
  },
  {
    "Name": "9mm pistol",
    "Damage": 16,
    "Exp": 0,
    "Reload": 1.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.13,
    "proj": 1,
    "Critical": 1,
    "CritDam": 16,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": "9mm round",
    "Type": "Grunt, Professional",
    "ClipSize": 20
  },
  {
    "Name": "A Light Shining in Darkness",
    "Damage": 33,
    "Exp": 0,
    "Reload": 1.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 4.38,
    "proj": 1,
    "Critical": 2,
    "CritDam": 33,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 15,
    "ammo": ".45 Auto",
    "Type": "Grunt, Professional",
    "ClipSize": 6
  },
  {
    "Name": "Hunting revolver",
    "Damage": 58,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.5,
    "proj": 1,
    "Critical": 1,
    "CritDam": 58,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 31,
    "ammo": ".45-70 Gov't",
    "Type": "Cowboy, Professional",
    "ClipSize": 6
  },
  {
    "Name": "Li'l Devil",
    "Damage": 45,
    "Exp": 0,
    "Reload": 1.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.25,
    "proj": 1,
    "Critical": 2,
    "CritDam": 45,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 15,
    "ammo": "12.7mm round",
    "Type": "Professional",
    "ClipSize": 7
  },
  {
    "Name": "Lucky",
    "Damage": 30,
    "Exp": 0,
    "Reload": 0.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.75,
    "proj": 1,
    "Critical": 2.5,
    "CritDam": 30,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": ".357 Magnum round",
    "Type": "Cowboy, Professional",
    "ClipSize": 6
  },
  {
    "Name": "Maria",
    "Damage": 20,
    "Exp": 0,
    "Reload": 1.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.75,
    "proj": 1,
    "Critical": 2,
    "CritDam": 20,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 15,
    "ammo": "9mm round",
    "Type": "Grunt, Professional",
    "ClipSize": 13
  },
  {
    "Name": "Mysterious Magnum",
    "Damage": 42,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.44,
    "proj": 1,
    "Critical": 1,
    "CritDam": 42,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": ".44 Magnum round",
    "Type": "Cowboy, Professional",
    "ClipSize": 6
  },
  {
    "Name": "Police pistol",
    "Damage": 30,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2,
    "proj": 1,
    "Critical": 1,
    "CritDam": 45,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 19,
    "ammo": ".357 Magnum round",
    "Type": "",
    "ClipSize": 6
  },
  {
    "Name": "Ranger Sequoia",
    "Damage": 62,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.69,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 62,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": ".45-70 Gov't",
    "Type": "Cowboy, Professional",
    "ClipSize": 5
  },
  {
    "Name": "Silenced .22 pistol",
    "Damage": 9,
    "Exp": 0,
    "Reload": 1.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.5,
    "proj": 1,
    "Critical": 3,
    "CritDam": 18,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": ".22LR round",
    "Type": "Professional",
    "ClipSize": 16
  },
  {
    "Name": "That Gun",
    "Damage": 30,
    "Exp": 0,
    "Reload": 2.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 2.5,
    "CritDam": 30,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 19,
    "ammo": "5.56mm round",
    "Type": "Cowboy",
    "ClipSize": 5
  },
  {
    "Name": "Weathered 10mm pistol",
    "Damage": 24,
    "Exp": 0,
    "Reload": 1.3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.75,
    "proj": 1,
    "Critical": 1,
    "CritDam": 24,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": "10mm round",
    "Type": "",
    "ClipSize": 16
  },
  {
    "Name": "Abilene Kid LE BB gun",
    "Damage": 4,
    "Exp": 0,
    "Reload": 3.3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.54,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 70,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "BBs",
    "Type": "Cowboy",
    "ClipSize": 100
  },
  {
    "Name": "All-American",
    "Damage": 26,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 6,
    "proj": 1,
    "Critical": 1,
    "CritDam": 26,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 13,
    "ammo": "5.56mm round",
    "Type": "Grunt",
    "ClipSize": 24
  },
  {
    "Name": "Anti-Materiel Rifle",
    "Damage": 110,
    "Exp": 0,
    "Reload": 2.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.54,
    "proj": 1,
    "Critical": 1,
    "CritDam": 110,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 55,
    "ammo": ".50 MG",
    "Type": "",
    "ClipSize": 8
  },
  {
    "Name": "Assault Carbine",
    "Damage": 13,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 14.4,
    "proj": 1,
    "Critical": 1,
    "CritDam": 13,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "5mm round",
    "Type": "Grunt, Auto",
    "ClipSize": 30
  },
  {
    "Name": "Automatic rifle",
    "Damage": 40,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 6.6,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 40,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": ".308 round",
    "Type": "Auto",
    "ClipSize": 20
  },
  {
    "Name": "BB gun",
    "Damage": 4,
    "Exp": 0,
    "Reload": 3.3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.54,
    "proj": 1,
    "Critical": 1,
    "CritDam": 4,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "BBs",
    "Type": "Cowboy",
    "ClipSize": 100
  },
  {
    "Name": "Battle rifle",
    "Damage": 48,
    "Exp": 0,
    "Reload": 1.9,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.93,
    "proj": 1,
    "Critical": 1,
    "CritDam": 48,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": ".308 round",
    "Type": "",
    "ClipSize": 8
  },
  {
    "Name": "Bozar",
    "Damage": 19,
    "Exp": 0,
    "Reload": 2.2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 15,
    "proj": 1,
    "Critical": 1,
    "CritDam": 19,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 18,
    "ammo": "5.56mm round",
    "Type": "Auto",
    "ClipSize": 30
  },
  {
    "Name": "Brush gun",
    "Damage": 75,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.23,
    "proj": 1,
    "Critical": 1,
    "CritDam": 75,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 33,
    "ammo": ".45-70 Gov't",
    "Type": "Cowboy",
    "ClipSize": 6
  },
  {
    "Name": "Christine's CoS silencer rifle",
    "Damage": 62,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.61,
    "proj": 1,
    "Critical": 2.5,
    "CritDam": 62,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 38,
    "ammo": ".308 round",
    "Type": "",
    "ClipSize": 5
  },
  {
    "Name": "Cowboy repeater",
    "Damage": 32,
    "Exp": 0,
    "Reload": 5.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.03,
    "proj": 1,
    "Critical": 1.25,
    "CritDam": 32,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 27,
    "ammo": ".357 Magnum round",
    "Type": "Cowboy",
    "ClipSize": 11
  },
  {
    "Name": "Gobi Campaign scout rifle",
    "Damage": 48,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.14,
    "proj": 1,
    "Critical": 2,
    "CritDam": 80,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": ".308 round",
    "Type": "",
    "ClipSize": 6
  },
  {
    "Name": "Hunting rifle",
    "Damage": 52,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.26,
    "proj": 1,
    "Critical": 2,
    "CritDam": 52,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 40,
    "ammo": ".308 round",
    "Type": "",
    "ClipSize": 10
  },
  {
    "Name": "La Longue Carabine",
    "Damage": 35,
    "Exp": 0,
    "Reload": 3.3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.15,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 35,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": ".357 Magnum round",
    "Type": "Cowboy",
    "ClipSize": 11
  },
  {
    "Name": "Light machine gun",
    "Damage": 21,
    "Exp": 0,
    "Reload": 2.2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 12,
    "proj": 1,
    "Critical": 1,
    "CritDam": 21,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 18,
    "ammo": "5.56mm round",
    "Type": "Grunt, Auto",
    "ClipSize": 200
  },
  {
    "Name": "Marksman carbine",
    "Damage": 24,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 5.7,
    "proj": 1,
    "Critical": 1,
    "CritDam": 24,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 14,
    "ammo": "5.56mm round",
    "Type": "Grunt",
    "ClipSize": 20
  },
  {
    "Name": "Medicine Stick",
    "Damage": 78,
    "Exp": 0,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.38,
    "proj": 1,
    "Critical": 1,
    "CritDam": 78,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 31,
    "ammo": ".45-70 Gov't",
    "Type": "Cowboy",
    "ClipSize": 8
  },
  {
    "Name": "Paciencia",
    "Damage": 55,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.18,
    "proj": 1,
    "Critical": 2,
    "CritDam": 110,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": ".308 round",
    "Type": "",
    "ClipSize": 3
  },
  {
    "Name": "Ratslayer",
    "Damage": 23,
    "Exp": 0,
    "Reload": 2.2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.3,
    "proj": 1,
    "Critical": 5,
    "CritDam": 23,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 33,
    "ammo": "5.56mm round",
    "Type": "",
    "ClipSize": 8
  },
  {
    "Name": "Service Rifle",
    "Damage": 18,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 5.46,
    "proj": 1,
    "Critical": 1,
    "CritDam": 18,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 15,
    "ammo": "5.56mm round",
    "Type": "Grunt",
    "ClipSize": 20
  },
  {
    "Name": "Sniper rifle",
    "Damage": 45,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.93,
    "proj": 1,
    "Critical": 2,
    "CritDam": 45,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 27,
    "ammo": ".308 round",
    "Type": "",
    "ClipSize": 5
  },
  {
    "Name": "Survivalist's Rifle",
    "Damage": 48,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.9,
    "proj": 1,
    "Critical": 1,
    "CritDam": 48,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "12.7mm round",
    "Type": "Grunt",
    "ClipSize": 10
  },
  {
    "Name": "This Machine",
    "Damage": 55,
    "Exp": 0,
    "Reload": 1.9,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.14,
    "proj": 1,
    "Critical": 1,
    "CritDam": 55,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": ".308 round",
    "Type": "",
    "ClipSize": 8
  },
  {
    "Name": "Trail carbine",
    "Damage": 48,
    "Exp": 0,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.54,
    "proj": 1,
    "Critical": 1,
    "CritDam": 48,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 29,
    "ammo": ".44 Magnum round",
    "Type": "Cowboy",
    "ClipSize": 8
  },
  {
    "Name": "Varmint Rifle",
    "Damage": 18,
    "Exp": 0,
    "Reload": 2.2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.22,
    "proj": 1,
    "Critical": 1,
    "CritDam": 18,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "5.56mm round",
    "Type": "",
    "ClipSize": 8
  },
  {
    "Name": ".45 Auto submachine gun",
    "Damage": 26,
    "Exp": 0,
    "Reload": 2.2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 11,
    "proj": 1,
    "Critical": 1,
    "CritDam": 26,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 19,
    "ammo": ".45 Auto",
    "Type": "Grunt, Professional, Auto",
    "ClipSize": 50
  },
  {
    "Name": "10mm submachine gun",
    "Damage": 19,
    "Exp": 0,
    "Reload": 2.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 9,
    "proj": 1,
    "Critical": 1,
    "CritDam": 19,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "10mm round",
    "Type": "Professional, Auto",
    "ClipSize": 40
  },
  {
    "Name": "12.7mm submachine gun",
    "Damage": 36,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 9,
    "proj": 1,
    "Critical": 1,
    "CritDam": 36,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "12.7mm round",
    "Type": "Professional, Auto",
    "ClipSize": 27
  },
  {
    "Name": "9mm submachine gun",
    "Damage": 14,
    "Exp": 0,
    "Reload": 2.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 14.3,
    "proj": 1,
    "Critical": 1,
    "CritDam": 14,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "9mm round",
    "Type": "Grunt, Professional, Auto",
    "ClipSize": 60
  },
  {
    "Name": "H&H Tools nail gun",
    "Damage": 9,
    "Exp": 0,
    "Reload": 2.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 14,
    "proj": 1,
    "Critical": 2,
    "CritDam": 9,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "Nails",
    "Type": "Professional, Auto",
    "ClipSize": 90
  },
  {
    "Name": "Silenced .22 SMG",
    "Damage": 10,
    "Exp": 0,
    "Reload": 2.3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 11,
    "proj": 1,
    "Critical": 3,
    "CritDam": 20,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 19,
    "ammo": ".22LR round",
    "Type": "Professional, Auto",
    "ClipSize": 240
  },
  {
    "Name": "Sleepytyme",
    "Damage": 22,
    "Exp": 0,
    "Reload": 2.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 10,
    "proj": 1,
    "Critical": 1,
    "CritDam": 22,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "10mm round",
    "Type": "Professional, Auto",
    "ClipSize": 40
  },
  {
    "Name": "Vance's 9mm submachine gun",
    "Damage": 17,
    "Exp": 0,
    "Reload": 2.7,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 13,
    "proj": 1,
    "Critical": 1,
    "CritDam": 17,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "9mm round",
    "Type": "Grunt, Professional, Auto",
    "ClipSize": 60
  },
  {
    "Name": "Big Boomer",
    "Damage": 60,
    "Exp": 0,
    "Reload": 3.1,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.58,
    "proj": 2,
    "Critical": 1,
    "CritDam": 9,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "12 gauge shotgun shell",
    "Type": "Shotgun",
    "ClipSize": 1
  },
  {
    "Name": "Caravan shotgun",
    "Damage": 45,
    "Exp": 0,
    "Reload": 1.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.21,
    "proj": 1,
    "Critical": 1,
    "CritDam": 6,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "20 gauge shotgun shell",
    "Type": "Shotgun",
    "ClipSize": 2
  },
  {
    "Name": "Dinner Bell",
    "Damage": 75,
    "Exp": 0,
    "Reload": 2.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.67,
    "proj": 1,
    "Critical": 1,
    "CritDam": 11,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "12 gauge shotgun shell",
    "Type": "Shotgun",
    "ClipSize": 5
  },
  {
    "Name": "Hunting shotgun",
    "Damage": 70,
    "Exp": 0,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.67,
    "proj": 1,
    "Critical": 1,
    "CritDam": 10,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "12 gauge shotgun shell",
    "Type": "Shotgun",
    "ClipSize": 8
  },
  {
    "Name": "Lever-action shotgun",
    "Damage": 48,
    "Exp": 0,
    "Reload": 2.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.77,
    "proj": 1,
    "Critical": 1,
    "CritDam": 7,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "20 gauge shotgun shell",
    "Type": "Cowboy, Shotgun",
    "ClipSize": 5
  },
  {
    "Name": "Riot shotgun",
    "Damage": 67,
    "Exp": 0,
    "Reload": 2.2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 4,
    "proj": 1,
    "Critical": 1,
    "CritDam": 10,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": "12 gauge shotgun shell",
    "Type": "Shotgun",
    "ClipSize": 12
  },
  {
    "Name": "Sawed-off shotgun",
    "Damage": 50,
    "Exp": 0,
    "Reload": 3.1,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.34,
    "proj": 2,
    "Critical": 1,
    "CritDam": 7,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 37,
    "ammo": "12 gauge shotgun shell",
    "Type": "Shotgun",
    "ClipSize": 1
  },
  {
    "Name": "Single shotgun",
    "Damage": 50,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.57,
    "proj": 1,
    "Critical": 1,
    "CritDam": 7,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 45,
    "ammo": "20 gauge shotgun shell",
    "Type": "Shotgun",
    "ClipSize": 1
  },
  {
    "Name": "Sturdy caravan shotgun",
    "Damage": 50,
    "Exp": 0,
    "Reload": 1.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.21,
    "proj": 1,
    "Critical": 1,
    "CritDam": 7,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 27,
    "ammo": "20 gauge shotgun shell",
    "Type": "",
    "ClipSize": 2
  },
  {
    "Name": "Arc welder",
    "Damage": 9,
    "Exp": 0,
    "Reload": 1.5,
    "dot": null,
    "robot": 8,
    "PA": 4,
    "Attackspeed": 8,
    "proj": 1,
    "Critical": 4,
    "CritDam": 1,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Electron charge pack",
    "Type": "Laser",
    "ClipSize": 30
  },
  {
    "Name": "CZ57 Avenger",
    "Damage": 13,
    "Exp": 0,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 30,
    "proj": 1,
    "Critical": 0.5,
    "CritDam": 13,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "5mm round",
    "Type": "Auto",
    "ClipSize": 120
  },
  {
    "Name": "Cleansing Flame",
    "Damage": 15,
    "Exp": 0,
    "Reload": 1.5,
    "dot": 10,
    "robot": null,
    "PA": null,
    "Attackspeed": 7,
    "proj": 1,
    "Critical": 1,
    "CritDam": 1,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 55,
    "ammo": "Flamer fuel",
    "Type": "Auto, Pyro, Energy",
    "ClipSize": 100
  },
  {
    "Name": "Elijah's jury-rigged Tesla cannon",
    "Damage": 85,
    "Exp": 0,
    "Reload": 3.2,
    "dot": 20,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.58,
    "proj": 1,
    "Critical": 2,
    "CritDam": 45,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 37,
    "ammo": "Electron charge pack",
    "Type": "Energy",
    "ClipSize": 6
  },
  {
    "Name": "FIDO",
    "Damage": 36,
    "Exp": 0,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 7,
    "proj": 1,
    "Critical": 0.5,
    "CritDam": 18,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": ".44 Magnum round",
    "Type": "Auto, Pyro",
    "ClipSize": 50
  },
  {
    "Name": "Flamer",
    "Damage": 16,
    "Exp": 0,
    "Reload": 1.5,
    "dot": 2,
    "robot": null,
    "PA": null,
    "Attackspeed": 8,
    "proj": 1,
    "Critical": 4,
    "CritDam": 1,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 50,
    "ammo": "Flamer fuel",
    "Type": "Auto, Energy",
    "ClipSize": 120
  },
  {
    "Name": "Gatling laser",
    "Damage": 13,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 30,
    "proj": 1,
    "Critical": 1,
    "CritDam": 10,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Electron charge pack",
    "Type": "Laser, Auto",
    "ClipSize": 240
  },
  {
    "Name": "Heavy incinerator",
    "Damage": 15,
    "Exp": 20,
    "Reload": 1.5,
    "dot": 8,
    "robot": null,
    "PA": null,
    "Attackspeed": 4,
    "proj": 1,
    "Critical": 4,
    "CritDam": 5,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 50,
    "ammo": "Flamer fuel",
    "Type": "Auto, Pyro, Energy",
    "ClipSize": 24
  },
  {
    "Name": "Incinerator",
    "Damage": 1,
    "Exp": 20,
    "Reload": 1.5,
    "dot": 4,
    "robot": null,
    "PA": null,
    "Attackspeed": 2,
    "proj": 1,
    "Critical": 4,
    "CritDam": 1,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 50,
    "ammo": "Flamer fuel",
    "Type": "Auto, Pyro, Energy",
    "ClipSize": 30
  },
  {
    "Name": "K9000 cyberdog gun",
    "Damage": 28,
    "Exp": 0,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 9.8,
    "proj": 1,
    "Critical": 0.5,
    "CritDam": 13,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 27,
    "ammo": ".357 Magnum round",
    "Type": "Auto",
    "ClipSize": 50
  },
  {
    "Name": "Minigun",
    "Damage": 12,
    "Exp": 0,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 25,
    "proj": 1,
    "Critical": 0.5,
    "CritDam": 12,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "5mm round",
    "Type": "Auto",
    "ClipSize": 240
  },
  {
    "Name": "Plasma caster",
    "Damage": 65,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.75,
    "proj": 1,
    "Critical": 1,
    "CritDam": 65,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "Microfusion cell",
    "Type": "Energy",
    "ClipSize": 10
  },
  {
    "Name": "Shoulder mounted machine gun",
    "Damage": 30,
    "Exp": 0,
    "Reload": 2.8,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 7,
    "proj": 1,
    "Critical": 0,
    "CritDam": 20,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "10mm round",
    "Type": "Auto",
    "ClipSize": 75
  },
  {
    "Name": "Sprtel-Wood 9700",
    "Damage": 16,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 20,
    "proj": 1,
    "Critical": 1,
    "CritDam": 16,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Electron charge pack",
    "Type": "Laser, Auto",
    "ClipSize": 90
  },
  {
    "Name": "Tesla Cannon",
    "Damage": 80,
    "Exp": 0,
    "Reload": 3.2,
    "dot": 20,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.34,
    "proj": 1,
    "Critical": 2,
    "CritDam": 40,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 37,
    "ammo": "Electron charge pack",
    "Type": "Energy",
    "ClipSize": 4
  },
  {
    "Name": "Tesla-Beaton prototype",
    "Damage": 90,
    "Exp": 0,
    "Reload": 3.2,
    "dot": 20,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.34,
    "proj": 1,
    "Critical": 2,
    "CritDam": 45,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 37,
    "ammo": "Electron charge pack",
    "Type": "Energy",
    "ClipSize": 4
  },
  {
    "Name": "The Smitty Special",
    "Damage": 35,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 7,
    "proj": 1,
    "Critical": 1,
    "CritDam": 35,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Microfusion cell",
    "Type": "Auto, Energy",
    "ClipSize": 20
  },
  {
    "Name": "Alien blaster",
    "Damage": 75,
    "Exp": 0,
    "Reload": 2.3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.75,
    "proj": 1,
    "Critical": 100,
    "CritDam": 50,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "Alien power cell",
    "Type": "Professional, Energy",
    "ClipSize": 10
  },
  {
    "Name": "Compliance Regulator",
    "Damage": 8,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.75,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 12,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 15,
    "ammo": "Energy cell",
    "Type": "Laser, Professional, Auto",
    "ClipSize": 30
  },
  {
    "Name": "Flare gun",
    "Damage": 10,
    "Exp": 0,
    "Reload": 2.3,
    "dot": 1,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.75,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 10,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Flamer fuel",
    "Type": "Pyro, Energy",
    "ClipSize": 1
  },
  {
    "Name": "Laser pistol",
    "Damage": 15,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.75,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 12,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 15,
    "ammo": "Energy cell",
    "Type": "Laser, Professional",
    "ClipSize": 30
  },
  {
    "Name": "MF Hyperbreeder Alpha",
    "Damage": 25,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 7,
    "proj": 1,
    "Critical": 2,
    "CritDam": 25,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "Microfusion breeder",
    "Type": "Laser, Professional, Auto",
    "ClipSize": 10
  },
  {
    "Name": "Missing laser pistol",
    "Damage": 11,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.75,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 11,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 15,
    "ammo": "Energy cell",
    "Type": "Laser",
    "ClipSize": 30
  },
  {
    "Name": "Pew Pew",
    "Damage": 75,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2,
    "proj": 1,
    "Critical": 2.5,
    "CritDam": 50,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "Energy cell",
    "Type": "Laser, Professional",
    "ClipSize": 2
  },
  {
    "Name": "Pulse gun",
    "Damage": 5,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": 250,
    "PA": 110,
    "Attackspeed": 1.03,
    "proj": 1,
    "Critical": 1,
    "CritDam": 5,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "Energy cell",
    "Type": "Laser, Professional",
    "ClipSize": 5
  },
  {
    "Name": "Recharger pistol",
    "Damage": 18,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 5,
    "proj": 1,
    "Critical": 1.2,
    "CritDam": 18,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 13,
    "ammo": "Microfusion breeder",
    "Type": "Professional, Energy",
    "ClipSize": 20
  },
  {
    "Name": "Sonic Emitter - Gabriel's Bark",
    "Damage": 55,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 1.03,
    "proj": 1,
    "Critical": 1,
    "CritDam": 25,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Energy cell",
    "Type": "Laser, Professional",
    "ClipSize": 12
  },
  {
    "Name": "Sonic Emitter - Opera Singer",
    "Damage": 55,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 1.03,
    "proj": 1,
    "Critical": 1,
    "CritDam": 25,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Energy cell",
    "Type": "Laser, Professional",
    "ClipSize": 24
  },
  {
    "Name": "Sonic Emitter - Revelation",
    "Damage": 31,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 1.03,
    "proj": 1,
    "Critical": 1,
    "CritDam": 18,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Energy cell",
    "Type": "Laser, Professional",
    "ClipSize": 24
  },
  {
    "Name": "Sonic Emitter - Robo-Scorpion",
    "Damage": 65,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 1.03,
    "proj": 1,
    "Critical": 1,
    "CritDam": 30,
    "CritExp": 100,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Energy cell",
    "Type": "Laser, Professional",
    "ClipSize": 8
  },
  {
    "Name": "Sonic Emitter - Tarantula",
    "Damage": 60,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 1.03,
    "proj": 1,
    "Critical": 1,
    "CritDam": 30,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Energy cell",
    "Type": "Laser, Professional, Pyro",
    "ClipSize": 8
  },
  {
    "Name": "AER14 prototype",
    "Damage": 35,
    "Exp": 0,
    "Reload": 2.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 2,
    "CritDam": 35,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "Microfusion cell",
    "Type": "Laser",
    "ClipSize": 12
  },
  {
    "Name": "Elijah's advanced LAER",
    "Damage": 65,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.75,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 32,
    "ammo": "Microfusion cell",
    "Type": "Laser",
    "ClipSize": 15
  },
  {
    "Name": "Elijah's advanced LAER split",
    "Damage": 28.2,
    "Exp": 0,
    "Reload": 2.3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.75,
    "proj": 3,
    "Critical": 1.5,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 32,
    "ammo": "Microfusion cell",
    "Type": "Laser",
    "ClipSize": 15
  },
  {
    "Name": "Gauss Rifle",
    "Damage": 120,
    "Exp": 0,
    "Reload": 2.3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 2,
    "CritDam": 60,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 40,
    "ammo": "Microfusion cell",
    "Type": "Energy",
    "ClipSize": 1
  },
  {
    "Name": "Holorifle",
    "Damage": 105,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.11,
    "proj": 1,
    "Critical": 1,
    "CritDam": 80,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Microfusion cell",
    "Type": "Energy",
    "ClipSize": 4
  },
  {
    "Name": "LAER",
    "Damage": 65,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.5,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 32,
    "ammo": "Microfusion cell",
    "Type": "Laser",
    "ClipSize": 20
  },
  {
    "Name": "LAER split",
    "Damage": 28.2,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.5,
    "proj": 3,
    "Critical": 1.5,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 32,
    "ammo": "Microfusion cell",
    "Type": "Laser",
    "ClipSize": 20
  },
  {
    "Name": "Laser RCW",
    "Damage": 15,
    "Exp": 0,
    "Reload": 1.8,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 9,
    "proj": 1,
    "Critical": 0.5,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "Electron charge pack",
    "Type": "Laser, Professional",
    "ClipSize": 60
  },
  {
    "Name": "Laser rifle",
    "Damage": 25,
    "Exp": 0,
    "Reload": 2.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.08,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 22,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 18,
    "ammo": "Microfusion cell",
    "Type": "Laser",
    "ClipSize": 24
  },
  {
    "Name": "Laser rifle split",
    "Damage": 15.8,
    "Exp": 0,
    "Reload": 2.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.08,
    "proj": 2,
    "Critical": 1.5,
    "CritDam": 22,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 18,
    "ammo": "Microfusion cell",
    "Type": "Laser",
    "ClipSize": 24
  },
  {
    "Name": "Recharger rifle",
    "Damage": 12,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 4.26,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 12,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 19,
    "ammo": "Microfusion breeder",
    "Type": "Energy",
    "ClipSize": 7
  },
  {
    "Name": "Tri-beam laser rifle",
    "Damage": 25,
    "Exp": 0,
    "Reload": 2.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.73,
    "proj": 3,
    "Critical": 1.5,
    "CritDam": 22,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 23,
    "ammo": "Microfusion cell",
    "Type": "Laser",
    "ClipSize": 16
  },
  {
    "Name": "Van Graff laser rifle",
    "Damage": 15,
    "Exp": 0,
    "Reload": 2.5,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.08,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 18,
    "ammo": "Microfusion cell",
    "Type": "Laser",
    "ClipSize": 24
  },
  {
    "Name": "YCS\\186",
    "Damage": 140,
    "Exp": 0,
    "Reload": 2.3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 2,
    "CritDam": 70,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 40,
    "ammo": "Microfusion cell",
    "Type": "Energy",
    "ClipSize": 1
  },
  {
    "Name": "Plasma Defender",
    "Damage": 38,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.5,
    "proj": 1,
    "Critical": 1,
    "CritDam": 38,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "Energy cell",
    "Type": "Professional, Energy",
    "ClipSize": 16
  },
  {
    "Name": "Plasma pistol",
    "Damage": 40,
    "Exp": 0,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.75,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 33,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Energy cell",
    "Type": "Professional, Energy",
    "ClipSize": 16
  },
  {
    "Name": "Multiplas rifle",
    "Damage": 35,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1,
    "proj": 3,
    "Critical": 1,
    "CritDam": 34,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "Microfusion cell",
    "Type": "Energy",
    "ClipSize": 10
  },
  {
    "Name": "Plasma rifle",
    "Damage": 47,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.4,
    "proj": 1,
    "Critical": 2,
    "CritDam": 47,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Microfusion cell",
    "Type": "Energy",
    "ClipSize": 12
  },
  {
    "Name": "Q-35 matter modulator",
    "Damage": 40,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.4,
    "proj": 1,
    "Critical": 2,
    "CritDam": 62,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "Microfusion cell",
    "Type": "Energy",
    "ClipSize": 12
  },
  {
    "Name": "Van Graff plasma rifle",
    "Damage": 32,
    "Exp": 0,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.4,
    "proj": 1,
    "Critical": 2,
    "CritDam": 32,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 30,
    "ammo": "Microfusion cell",
    "Type": "Energy",
    "ClipSize": 12
  },
  {
    "Name": "25mm grenade APW",
    "Damage": 2,
    "Exp": 50,
    "Reload": 2.2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.13,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "25mm grenade",
    "Type": "Explosive",
    "ClipSize": 8
  },
  {
    "Name": "Annabelle",
    "Damage": 150,
    "Exp": 200,
    "Reload": 4,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.89,
    "proj": 1,
    "Critical": 0,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 47,
    "ammo": "Missile",
    "Type": "Explosive",
    "ClipSize": 1
  },
  {
    "Name": "Esther",
    "Damage": 475,
    "Exp": 600,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.89,
    "proj": 1,
    "Critical": 0,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 55,
    "ammo": "Mini nuke",
    "Type": "Explosive",
    "ClipSize": 1
  },
  {
    "Name": "Fat Man",
    "Damage": 400,
    "Exp": 600,
    "Reload": 3,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.58,
    "proj": 1,
    "Critical": 0,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 65,
    "ammo": "Mini nuke",
    "Type": "Explosive",
    "ClipSize": 1
  },
  {
    "Name": "Great Bear grenade rifle",
    "Damage": 15,
    "Exp": 100,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.14,
    "proj": 1,
    "Critical": 1,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 32,
    "ammo": "40mm grenade",
    "Type": "Grunt, Explosive",
    "ClipSize": 1
  },
  {
    "Name": "Grenade launcher",
    "Damage": 30,
    "Exp": 100,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.56,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "40mm grenade",
    "Type": "Grunt, Explosive",
    "ClipSize": 1
  },
  {
    "Name": "Grenade machinegun",
    "Damage": 0,
    "Exp": 50,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 4.5,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 50,
    "ammo": "25mm grenade",
    "Type": "Auto, Explosive",
    "ClipSize": 30
  },
  {
    "Name": "Grenade rifle",
    "Damage": 2,
    "Exp": 100,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.14,
    "proj": 1,
    "Critical": 1,
    "CritDam": 1,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "40mm grenade",
    "Type": "Explosive",
    "ClipSize": 1
  },
  {
    "Name": "Mercenary's grenade rifle",
    "Damage": 2,
    "Exp": 100,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.14,
    "proj": 1,
    "Critical": 1,
    "CritDam": 1,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "40mm grenade",
    "Type": "Explosive",
    "ClipSize": 1
  },
  {
    "Name": "Mercy",
    "Damage": 5,
    "Exp": 100,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.1,
    "proj": 1,
    "Critical": 50,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 50,
    "ammo": "40mm grenade",
    "Type": "Auto, Explosive",
    "ClipSize": 18
  },
  {
    "Name": "Missile launcher",
    "Damage": 125,
    "Exp": 200,
    "Reload": 4,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.58,
    "proj": 1,
    "Critical": 0,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 55,
    "ammo": "Missile",
    "Type": "Explosive",
    "ClipSize": 1
  },
  {
    "Name": "Red Glare",
    "Damage": 20,
    "Exp": 40,
    "Reload": 6.8,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 5,
    "proj": 1,
    "Critical": 0,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "Rocket",
    "Type": "Auto, Explosive",
    "ClipSize": 13
  },
  {
    "Name": "Red Victory grenade rifle",
    "Damage": 2,
    "Exp": 100,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.21,
    "proj": 1,
    "Critical": 1,
    "CritDam": 1,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 29,
    "ammo": "40mm grenade",
    "Type": "Explosive",
    "ClipSize": 1
  },
  {
    "Name": "Thump-Thump",
    "Damage": 2,
    "Exp": 100,
    "Reload": 2,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.79,
    "proj": 1,
    "Critical": 1,
    "CritDam": 1,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "40mm grenade",
    "Type": "Grunt, Explosive",
    "ClipSize": 1
  },
  {
    "Name": "Dynamite",
    "Damage": 1,
    "Exp": 75,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.41,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Cowboy, Explosive"
  },
  {
    "Name": "Fire bomb",
    "Damage": 1,
    "Exp": 20,
    "dot": 4,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.41,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Cowboy, Throwing, Pyro, Explosive"
  },
  {
    "Name": "Frag grenade",
    "Damage": 1,
    "Exp": 125,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.65,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Grun, Throwing, Explosive"
  },
  {
    "Name": "Holy Frag Grenade",
    "Damage": 1,
    "Exp": 800,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.65,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Grunt, Throwing, Explosive"
  },
  {
    "Name": "Incendiary grenade",
    "Damage": 1,
    "Exp": 50,
    "dot": 6,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.65,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Pyro, Explosive"
  },
  {
    "Name": "Long-fuse dynamite",
    "Damage": 1,
    "Exp": 75,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.41,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Cowboy, Throwing, Explosive"
  },
  {
    "Name": "MFC grenade (Mad Bomber)",
    "Damage": 1,
    "Exp": 75,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.65,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "",
    "Type": "Throwing, Explosive"
  },
  {
    "Name": "Nuka-grenade",
    "Damage": 1,
    "Exp": 350,
    "dot": 2,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.65,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Throwing, Explosive"
  },
  {
    "Name": "Plasma grenade",
    "Damage": 1,
    "Exp": 225,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.65,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Throwing, Explosive"
  },
  {
    "Name": "Proton throwing axe",
    "Damage": 40,
    "Exp": 0,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 0.8,
    "proj": 1,
    "Critical": 1,
    "CritDam": 29,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "",
    "Type": "Throwing, Melee"
  },
  {
    "Name": "Protonic inversal throwing axe",
    "Damage": 60,
    "Exp": 0,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 0.88,
    "proj": 1,
    "Critical": 1,
    "CritDam": 29,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Throwing, Melee"
  },
  {
    "Name": "Pulse grenade",
    "Damage": 1,
    "Exp": 10,
    "dot": null,
    "robot": 200,
    "PA": 80,
    "Attackspeed": 0.65,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Throwing, Explosive"
  },
  {
    "Name": "Throwing hatchet",
    "Damage": 20,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.88,
    "proj": 1,
    "Critical": 1,
    "CritDam": 20,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Cowboy, Throwing, Melee"
  },
  {
    "Name": "Throwing knife",
    "Damage": 15,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.21,
    "proj": 1,
    "Critical": 2,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "",
    "Type": "Cowboy, Throwing, Melee"
  },
  {
    "Name": "Throwing knife spear",
    "Damage": 42,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.48,
    "proj": 1,
    "Critical": 1,
    "CritDam": 42,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Throwing spear",
    "Damage": 50,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.6,
    "proj": 1,
    "Critical": 1,
    "CritDam": 50,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Throwing, Melee"
  },
  {
    "Name": "Tin grenade (Mad Bomber)",
    "Damage": 1,
    "Exp": 100,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.65,
    "proj": 1,
    "Critical": 1,
    "CritDam": 0,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "",
    "Type": "Throwing, Explosive"
  },
  {
    "Name": "Tomahawk",
    "Damage": 30,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 0.66,
    "proj": 1,
    "Critical": 1,
    "CritDam": 30,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 23,
    "ammo": "",
    "Type": "Cowboy, Throwing, Melee"
  },
  {
    "Name": "Blade of the East",
    "Damage": 65,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.5,
    "proj": 1,
    "Critical": 1,
    "CritDam": 30,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Blade of the West",
    "Damage": 60,
    "Exp": 0,
    "dot": 2,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.13,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 30,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 29,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Blood-Nap",
    "Damage": 30,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.69,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 45,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": "",
    "Type": "Cowboy, Melee"
  },
  {
    "Name": "Bowie knife",
    "Damage": 23,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.46,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 35,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "",
    "Type": "Cowboy, Melee"
  },
  {
    "Name": "Broad machete",
    "Damage": 15,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.23,
    "proj": 1,
    "Critical": 2,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Bumper sword",
    "Damage": 32,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.42,
    "proj": 1,
    "Critical": 1,
    "CritDam": 32,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 38,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Chainsaw",
    "Damage": 9.5,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 10,
    "proj": 1,
    "Critical": 1,
    "CritDam": 8,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 65,
    "ammo": "",
    "Type": "Auto, Melee"
  },
  {
    "Name": "Chance's knife",
    "Damage": 22,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 4.15,
    "proj": 1,
    "Critical": 2,
    "CritDam": 22,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": "",
    "Type": "Cowboy, Grunt, Melee"
  },
  {
    "Name": "Chopper",
    "Damage": 14,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.92,
    "proj": 1,
    "Critical": 2,
    "CritDam": 14,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Cleaver",
    "Damage": 7,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.54,
    "proj": 1,
    "Critical": 1,
    "CritDam": 7,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Combat knife",
    "Damage": 15,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.23,
    "proj": 1,
    "Critical": 2,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": "",
    "Type": "Cowboy, Grunt, Melee"
  },
  {
    "Name": "Cosmic knife",
    "Damage": 12,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 1,
    "CritDam": 12,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Cosmic knife clean",
    "Damage": 15,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 1.2,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Cosmic knife super-heated",
    "Damage": 14,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 5,
    "CritDam": 14,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Figaro",
    "Damage": 8,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 4.15,
    "proj": 1,
    "Critical": 4,
    "CritDam": 16,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 17,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Fire axe",
    "Damage": 55,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.58,
    "proj": 1,
    "Critical": 1,
    "CritDam": 27,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Gehenna",
    "Damage": 42,
    "Exp": 0,
    "dot": 5,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.77,
    "proj": 1,
    "Critical": 2,
    "CritDam": 21,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "",
    "Type": "Pyro, Melee"
  },
  {
    "Name": "Hatchet",
    "Damage": 16,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.54,
    "proj": 1,
    "Critical": 1,
    "CritDam": 16,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Cowboy, Melee"
  },
  {
    "Name": "Katana",
    "Damage": 27,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.88,
    "proj": 1,
    "Critical": 2,
    "CritDam": 22,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 21,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Knife",
    "Damage": 8,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 1,
    "CritDam": 8,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "",
    "Type": "Cowboy, Melee"
  },
  {
    "Name": "Knife spear",
    "Damage": 20,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.89,
    "proj": 1,
    "Critical": 1,
    "CritDam": 20,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Knife spear clean",
    "Damage": 25,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.89,
    "proj": 1,
    "Critical": 1.2,
    "CritDam": 25,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Knock-Knock",
    "Damage": 66,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.8,
    "proj": 1,
    "Critical": 1,
    "CritDam": 33,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 21,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Liberator",
    "Damage": 18,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.46,
    "proj": 1,
    "Critical": 3,
    "CritDam": 18,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 18,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Machete",
    "Damage": 11,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 11,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Machete gladius",
    "Damage": 28,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 28,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Proton axe",
    "Damage": 50,
    "Exp": 0,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 1.91,
    "proj": 1,
    "Critical": 1,
    "CritDam": 25,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Protonic inversal axe",
    "Damage": 58,
    "Exp": 0,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 1.91,
    "proj": 1,
    "Critical": 1,
    "CritDam": 45,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Ripper",
    "Damage": 6,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 10,
    "proj": 1,
    "Critical": 1,
    "CritDam": 5,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 65,
    "ammo": "",
    "Type": "Auto, Melee"
  },
  {
    "Name": "Shishkebab",
    "Damage": 40,
    "Exp": 0,
    "dot": 2,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.31,
    "proj": 1,
    "Critical": 2,
    "CritDam": 20,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Pyro, Melee"
  },
  {
    "Name": "Straight razor",
    "Damage": 5,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.69,
    "proj": 1,
    "Critical": 2,
    "CritDam": 10,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 18,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Switchblade",
    "Damage": 7,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2,
    "proj": 1,
    "Critical": 2,
    "CritDam": 11,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 18,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Thermic lance",
    "Damage": 10,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 10,
    "proj": 1,
    "Critical": 1,
    "CritDam": 10,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 65,
    "ammo": "",
    "Type": "Auto, Melee"
  },
  {
    "Name": "9 iron",
    "Damage": 17,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.25,
    "proj": 1,
    "Critical": 1,
    "CritDam": 17,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Baseball bat",
    "Damage": 28,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.98,
    "proj": 1,
    "Critical": 1,
    "CritDam": 22,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Cattle prod",
    "Damage": 5,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.31,
    "proj": 1,
    "Critical": 2,
    "CritDam": 5,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Dress cane",
    "Damage": 22,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.31,
    "proj": 1,
    "Critical": 1,
    "CritDam": 35,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 27,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Lead pipe",
    "Damage": 22,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.54,
    "proj": 1,
    "Critical": 1,
    "CritDam": 22,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Nail board",
    "Damage": 25,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.42,
    "proj": 1,
    "Critical": 0,
    "CritDam": 25,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 27,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Nephi's golf driver",
    "Damage": 30,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.25,
    "proj": 1,
    "Critical": 1.2,
    "CritDam": 30,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 21,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Nuka Breaker",
    "Damage": 50,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.44,
    "proj": 1,
    "Critical": 2,
    "CritDam": 50,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Oh, Baby!",
    "Damage": 80,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.74,
    "proj": 1,
    "Critical": 1,
    "CritDam": 40,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Old Glory",
    "Damage": 45,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.89,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 80,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Police baton",
    "Damage": 10,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.77,
    "proj": 1,
    "Critical": 1,
    "CritDam": 10,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 23,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Pool cue",
    "Damage": 15,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.58,
    "proj": 1,
    "Critical": 0,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 27,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Rebar club",
    "Damage": 42,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.26,
    "proj": 1,
    "Critical": 0.5,
    "CritDam": 24,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 40,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Rolling pin",
    "Damage": 3,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.73,
    "proj": 1,
    "Critical": 0,
    "CritDam": 8,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Shovel",
    "Damage": 12,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.74,
    "proj": 1,
    "Critical": 3,
    "CritDam": 20,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Sledgehammer",
    "Damage": 24,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.89,
    "proj": 1,
    "Critical": 1,
    "CritDam": 24,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 38,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Super sledge",
    "Damage": 70,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.58,
    "proj": 1,
    "Critical": 1,
    "CritDam": 35,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 38,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "The Humble Cudgel",
    "Damage": 26,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.77,
    "proj": 1,
    "Critical": 1,
    "CritDam": 26,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 21,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Tire iron",
    "Damage": 15,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.31,
    "proj": 1,
    "Critical": 1,
    "CritDam": 15,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 27,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "War club",
    "Damage": 24,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3.75,
    "proj": 1,
    "Critical": 1,
    "CritDam": 19,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 21,
    "ammo": "",
    "Type": "Cowboy, Melee"
  },
  {
    "Name": "X-2 antenna",
    "Damage": 65,
    "Exp": 0,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 1.08,
    "proj": 1,
    "Critical": 1,
    "CritDam": 23,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Melee"
  },
  {
    "Name": "Ballistic fist",
    "Damage": 80,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.09,
    "proj": 1,
    "Critical": 1,
    "CritDam": 80,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Bear trap fist",
    "Damage": 30,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.09,
    "proj": 1,
    "Critical": 1,
    "CritDam": 27,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Bladed gauntlet",
    "Damage": 25,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.57,
    "proj": 1,
    "Critical": 2,
    "CritDam": 40,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 26,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Boxing gloves",
    "Damage": 1,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.26,
    "proj": 1,
    "Critical": 1,
    "CritDam": 1,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Boxing tape",
    "Damage": 4,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.26,
    "proj": 1,
    "Critical": 1,
    "CritDam": 4,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Brass knuckles",
    "Damage": 18,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.05,
    "proj": 1,
    "Critical": 1,
    "CritDam": 18,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 18,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Corrosive glove",
    "Damage": 21,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.09,
    "proj": 1,
    "Critical": 1,
    "CritDam": 5,
    "CritExp": 0,
    "CritDot": 2,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Cram Opener",
    "Damage": 28,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.7,
    "proj": 1,
    "Critical": 2,
    "CritDam": 44,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 26,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Displacer glove",
    "Damage": 50,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.36,
    "proj": 1,
    "Critical": 1,
    "CritDam": 50,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Dog tag fist",
    "Damage": 20,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.58,
    "proj": 1,
    "Critical": 1,
    "CritDam": 20,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Dr. Klein's glove",
    "Damage": 34,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.36,
    "proj": 1,
    "Critical": 3,
    "CritDam": 5,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 18,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Dr. Mobius' glove",
    "Damage": 28,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.36,
    "proj": 1,
    "Critical": 2,
    "CritDam": 5,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 15,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Embrace of the Mantis King!",
    "Damage": 42,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.57,
    "proj": 1,
    "Critical": 3,
    "CritDam": 64,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Fist of Rawr",
    "Damage": 50,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.96,
    "proj": 1,
    "Critical": 2,
    "CritDam": 75,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 24,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Golden Gloves",
    "Damage": 1,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.26,
    "proj": 1,
    "Critical": 2,
    "CritDam": 1,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Greased Lightning",
    "Damage": 32,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 3,
    "proj": 1,
    "Critical": 1,
    "CritDam": 32,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Industrial hand",
    "Damage": 5,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 10,
    "proj": 1,
    "Critical": 1,
    "CritDam": 40,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 65,
    "ammo": "",
    "Type": "Auto, Unarmed"
  },
  {
    "Name": "Love and Hate",
    "Damage": 30,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.53,
    "proj": 1,
    "Critical": 1,
    "CritDam": 30,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 19,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Mantis gauntlet",
    "Damage": 30,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.02,
    "proj": 1,
    "Critical": 3,
    "CritDam": 30,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Paladin Toaster",
    "Damage": 41,
    "Exp": 0,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 1.64,
    "proj": 1,
    "Critical": 1,
    "CritDam": 41,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Power fist",
    "Damage": 48,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.31,
    "proj": 1,
    "Critical": 1,
    "CritDam": 40,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Pushy",
    "Damage": 60,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.47,
    "proj": 1,
    "Critical": 1,
    "CritDam": 60,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Recompense of the Fallen",
    "Damage": 25,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.89,
    "proj": 1,
    "Critical": 1,
    "CritDam": 25,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 35,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Salt-Upon-Wounds' power fist",
    "Damage": 45,
    "Exp": 0,
    "dot": 3,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.36,
    "proj": 1,
    "Critical": 1,
    "CritDam": 45,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Saturnite fist",
    "Damage": 35,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.8,
    "proj": 1,
    "Critical": 1,
    "CritDam": 35,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 25,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Saturnite fist super-heated",
    "Damage": 55,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.65,
    "proj": 1,
    "Critical": 1,
    "CritDam": 55,
    "CritExp": 0,
    "CritDot": 2,
    "AP cost": 25,
    "ammo": "",
    "Type": "Pyro, Unarmed"
  },
  {
    "Name": "Scientist glove",
    "Damage": 21,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.36,
    "proj": 1,
    "Critical": 1.5,
    "CritDam": 5,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "She's Embrace",
    "Damage": 25,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.76,
    "proj": 1,
    "Critical": 3,
    "CritDam": 37,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 20,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Spiked knuckles",
    "Damage": 25,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 2.37,
    "proj": 1,
    "Critical": 1,
    "CritDam": 25,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 19,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Sterilizer glove",
    "Damage": 21,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.36,
    "proj": 1,
    "Critical": 1,
    "CritDam": 5,
    "CritExp": 0,
    "CritDot": 2,
    "AP cost": 28,
    "ammo": "",
    "Type": "Pyro, Unarmed"
  },
  {
    "Name": "Two-Step Goodbye",
    "Damage": 70,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.09,
    "proj": 1,
    "Critical": 4,
    "CritDam": 10,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Yao guai gauntlet",
    "Damage": 20,
    "Exp": 0,
    "dot": null,
    "robot": null,
    "PA": null,
    "Attackspeed": 1.63,
    "proj": 1,
    "Critical": 2.5,
    "CritDam": 30,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 22,
    "ammo": "",
    "Type": "Unarmed"
  },
  {
    "Name": "Zap glove",
    "Damage": 35,
    "Exp": 0,
    "dot": null,
    "robot": 50,
    "PA": 20,
    "Attackspeed": 1.64,
    "proj": 1,
    "Critical": 1,
    "CritDam": 35,
    "CritExp": 0,
    "CritDot": null,
    "AP cost": 28,
    "ammo": "",
    "Type": "Unarmed"
  }
]
